//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McpServices.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class McpTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal McpTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("McpServices.Resources.McpTexts", typeof(McpTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Api_Description {
            get {
                return ResourceManager.GetString("Api_Description", resourceCulture);
            }
        }
        
        public static string Api_Title {
            get {
                return ResourceManager.GetString("Api_Title", resourceCulture);
            }
        }
        
        public static string Scope_SystemFullAccess_Description {
            get {
                return ResourceManager.GetString("Scope_SystemFullAccess_Description", resourceCulture);
            }
        }
        
        public static string Scope_TenantFullAccess_Description {
            get {
                return ResourceManager.GetString("Scope_TenantFullAccess_Description", resourceCulture);
            }
        }
        
        public static string Scope_TenantReadonlyAccess_Description {
            get {
                return ResourceManager.GetString("Scope_TenantReadonlyAccess_Description", resourceCulture);
            }
        }
        
        public static string SwaggerClient_Description {
            get {
                return ResourceManager.GetString("SwaggerClient_Description", resourceCulture);
            }
        }
        
        public static string McpClient_Description {
            get {
                return ResourceManager.GetString("McpClient_Description", resourceCulture);
            }
        }
    }
}
